# Generated by Django 4.2.24 on 2025-10-27 00:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=255,
                unique=True,
                validators=[users.models.validate_gmail_domain],
            ),
        ),
    ]
