# Generated by Django 4.2.24 on 2025-10-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runs", "0005_alter_run_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="runinputfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("pdf", "PDF Document"),
                    ("image", "Image"),
                    ("text", "Text Summary"),
                    ("csv", "CSV File"),
                    ("excel", "Excel File"),
                    ("word", "Word Document"),
                ],
                max_length=10,
            ),
        ),
    ]
